### ISSUE TITLE
NPC Focus Rating Invisible

### ISSUE THREAD

**Issue by YeLomie** [CurtR95/FVTT-Dishonored#105]
**Browser:** Chrome
**Modules Installed:** Forien's Quest Log; FX Master; PDFoundry, Scene Transitions
**Steps for Reproduction:** Create a NPC character sheet and attempt to provide them with a _Focus_
**Expected Behaviour:** The Focus Rating will appear next to the Focus
**Actual Behaviour:** The Focus Rating is blank
![image](https://user-images.githubusercontent.com/87867375/126800021-b3568402-9e4d-422b-b39f-a7132bcdd696.png)

**Comment by CurtR95** [comment]
Hi @YeLomie,

Thanks for raising this, just to confirm this still occurs with all modules disabled also?

I suspect this is an issue with the NPC sheet and will try and have a look at this tomorrow!

Best Regards
カイト・リ９５
KaitoR95

**Comment by CurtR95** [comment]
Have investigated further, all stats (such as quantity, protection and damage) are broken. As is the equip/unequip.
