### ISSUE TITLE
Question - Group Momentum Pool

### ISSUE THREAD

**Issue by angrytramp** [CurtR95/FVTT-Dishonored#73]
Thanks @CurtR95 for this vtt system, really great!

I couldn't find a group Momentum pool, so I've added one similar to the Chaos pool. Would you be up for me adding a pull request for it?

Thanks.

**Comment by CurtR95** [comment]
Hi @angrytramp, sure! I think I put the momentum on the character sheets as an individual momentum. But you are correct this should be shared really! If you could pull it onto 0.3.1, I want to quickly go over the code and rip out the individual momentum (or at least put a system setting in) before I push it to master!

**Comment by angrytramp** [comment]
I've added this in the following PR. Let me know your thoughts!
#74

**Comment by CurtR95** [comment]
It looks good! I have made a couple of very small changes as follows:
- Removed the Individual Momentum
- Split the trackers into two sub windows
- Created a system setting to determine who can edit Momentum and who can edit Chaos. This does require one to be able to edit configuration settings.
- Removed None as an option for these two settings.
- Made the width of the windows smaller again (felt they were now too big - especially as two individual trackers)

Thank you so much for assisting with this!! It helps so much! If you would like I can add you as a contributor or in the thanks on the README. Just let me know if you would like that (and where you want me to link it to!).

I'll probably have a coding session tomorrow to which I'll release 0.3.1, this will include your code and a few other things hopefully.
